version: '3'
services: 
  web:
    container_name: burger-builder
    build: .
    image: burger-builder
    command: yarn start
    restart: always
    volumes: 
      - .:/app
      - /app/node_modules
    ports: 
      - "3000:3000"
    env_file:
      - .env
  db:
    container_name: burger-builder-db
    image: postgres:alpine
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file:
      - database.env

volumes:
  database-data: